sudo: required
language: node_js
node_js:
  - "4.2.1"
  - "6.9.1"
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
install:
    - git config --global user.email "test@test.com"
    - git config --global user.name "Travis CI Test"
    - export docuBranch=TravisCI
    - npm run prepare
after_script:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
script:
    - npm run init
    - npm run compile
    - npm run preparePushResult
    - npm run pushResult
