sudo: required
language: node_js
node_js:
  - "4.2.1"
  - "6.9.1"
install:
    - git config user.email "test@test.com"
    - git config user.name "Travis CI Test"
    - npm run prepare
script:
    - npm run init
    - npm run compile
    - npm run preparePushResult
    - npm run pushResult
