sudo: required
language: node_js
node_js:
- 6.9.1
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
install:
- git config --global user.email "test@test.com"
- git config --global user.name "Travis CI Test"
- export docuBranch=TravisCI
- npm run prepare
script:
- npm run init
- npm run compile
- npm run preparePushResult
- npm run pushResult
env:
  global:
  - secure: K4hLgviiLJ5Gh/x4YtgP3BHQkcTqkCkogkNJm87xlTfADX2VmXQwZ2LyusBn0l0Kut5zDLWk+/FTjsO7Q2l7yB3mWD0QtVqwZuWMsp3vHx+0uEL38cMo5U38JW5Y+9oX5dheIyQgxuZZ7oaxV/Z9OY2L+mW/ADUH1TXsRsKsCwfDXDLDK2MU4LeB2uwu0CgWWffzzbMJ7advg0oyJ73l6VOWBm+vXcjC8Psh5+AEPDpyd2GGUpyOuSjKgGuRAOWybUpK7FCjfzdvx2I0V5R91mjKhBpLh/pG6H2axUGA10qEA/WhfkAvxYzqKEs5sFMYKcpfXyyMeOEYCOvzetcdAxJhZhfckSfBM0q0t0PsZtqx6BIs3T8xeTwY9OOVoOwBpsYzQX0lSIwEjNy00O8pgeYFENYcmspuU1R/0PtZ8hheO/ijEnuXLGR+Q2edsSAicUYQ00UsaABE0nBg5nPAvKTuQGVjS/MnMCipm3pS7QFr0hHd51pdPUtaIDAeU+MXdqS7yrKUnpr/h6V9+qIXz41vpgmvQHjY1yKJRTheO0vxvW+dbNciLO7Die4HAbBIGyBx92TwWflnv2rNe3/1CS3CnzMkgw4ieRnM+Vsuryvz1z29OF9MpCYrtT3v7I9YhYUS50DegpS9SwxHyUZzcWSqEd4N8f8Q/hLeOuQQ3gY=
  - secure: EAhR9xsDGfDynNHwDHZ48/FTE1iwBzypDjSwXoIws2zWdeRuJwUbAq79sOaxITe11u/K5LeTVtyX6w51yt6uiWhyN7Zzu2RwXkyvrXSp1X49q3nV5OQS570Gb/mFjzUu1dmxR4C5YqpO1A4qEYxKIyIwL7RCTrIFTr+IbXtUxi+U4EYjsD1uGXGKtSKjToqNYK0NmaAELBNsywreteWlAUaInAs/mxtC+UHGJRaW0cmSa3yDWPPKre135V8dZHFTL9X0P6Z5KSECkUOBXpBlSo/H6o9njFU+IGMzmHS2pdArzM+SDUy1oMr+/NjGNZC3hqUhOHWH+etFrmG3skMnCjZsF91TUkVu05060I6MyX1gzNcliuSiCE13Ifh0xgWvpT/xM4jIMrFqfDFTxE3ryCeNIJX/uA4D3ziw4vEYy94mtdcr/LPvWOwN80IfXxxP1PmXkB2JW3u2cyHIBM1RIDuzkewwar/R1Lztbqk8rmMXD4qxxbfw0OT9XTxKl3lrZfltBQgaxi8ggq2HDSOBtTSgPec1wa4QbAdMyZ98iYAKb77pZ1fk0XwzuJDI968vgnjTYBZQ9gQ+L6cmD3JIXilM8bVKen1XN1sTZkpRoo8vq1za4/8pxgsJp9dOz1IlpJHG54i60GKrh7CtlfXDnUoLBOiWr9VwmsJ8A8nHHgI=
  - secure: msa0TCAGp5fPf4NuN5VW6aYXHgXk5uJYFoUVQZvZny9Z+rYO0IXLjCgNf/Az7oNGSOH914JqwEJWA8LLwZ3EQVEJpdUX9t3u6Di9zbZDZExqZcyoujd+hLK2uyKoZeW4zuonxHOptHlXBCU89wmUjpLngP6/bYjXunsw18pt+Z/AfkJ/tychzxynAdmQqe1WxBuD4ll1Rjxrku1ITPvUeQWP6FTFRxGBVAHdx9/QeWZ6p2yCVkwGQV5RI17KvnY8yxQm/G+hf46E4lhLI+alM/5iTdyB81XOhLC+PHbRwALNSRxJK6cnJ0du3TD3Og1PAvWvgMpX0b1aEkgv2zwjil/DMhASQjgdajmQPBWvy613eOudh10IFJIiBJFlEu1NhPAd72xzOFVBZWC/YACPv6E7sWUOTP2ZvDqOB5YWya0nfs4lfGTZ2suBOwHJo8Cj1n11dYj3ulVSQeXXETsYmp1xySU3mAu/wLfxmSy6gF0LhaoGRZprujGnXkmca+DxPJnjhc13DlcWqmr+dDrItrYPkfYm4Qup/18OkrVumwlBVCkelE5KJGuwZGK4B9k5lqqXdqyGr63FmUuz6H4QhZuUr027B2ZOlE5rnwMZK899F5jsx/xE/SaIkNimqeXccXiWB+WgsG8BhZxQkm/gZ5hKPz4mQa0+fVdyS//jdNg=
