sudo: required
language: node_js
node_js:
  - "4.2.1"
  - "6.9.1"
before_script: composer config github-oauth.github.com ${GH_TOKEN}
install:
    - git config --global user.email "test@test.com"
    - git config --global user.name "Travis CI Test"
    - export docuBranch=TravisCI
    - npm run prepare
script:
    - npm run init
    - npm run compile
    - npm run preparePushResult
    - npm run pushResult
