sudo: required
language: node_js
node_js:
- 6.9.1
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
install:
- git config --global user.email "test@test.com"
- git config --global user.name "Travis CI Test"
- export docuBranch=TravisCI
- npm run prepare
script:
- npm run init
- npm run compile
- npm run preparePushResult
- npm run pushResult
env:
  global:
    secure: "tuTNhyaNik+BpnJpRGP+cqgYk8fQnPWRF66Jg3nc0G8k/FdJrz+LHNYK07/NBRN34Fk7NEEiDD0t8LatG7TDUk9hyCeO6MVvk36JjGf1AI8eljQJ2AQw2wpM2RGnm/NfTKvOrTD9XiohRLtQz/B491lobaAW6wLBzK88qvPkx9oiYCMvHza/IiIKlqLVfmIsF9m10e+mmjMXl0KvB18YP2O3d91kitdJnbnY1eWXS9HmlUTVhpS0I8UkdxQeTwA1HvC2+/DsiadD2NKbwJhXt2++E/ylB8vdfVXn3J3UHkZhJPo70aAefIvyAcq4B1SAAd7we3/c7DFt5qoQ1ahtL5jCEMVOxGFsQjh20UXg+PF+r+jZYtXAJo3O82CbAKSGOiGkl22Fq4EyYToIyXsw6wewHAzIcnTfAmVaVcrWICBC6+lzlZXOwFN7WZ4sXG66C9aqQ5i4zAQiz43OexoeSPJLWczEIi1zg9Ym2mAzwYOjWGeEQkp96O+gfzMB/vbrEsxkltPYFaACouTOeVpKGMZMN1E2Cv4A+frYCUt1my6sdjQY0Q/J6y38F3L8EayU0sH/4loP8f/fZrJHhg3g0WpBh7Q2cbOApV5grwsCiszjKhzaW3bD8iXcbzb2CeNIVj4A0EKTs9jWTIhRwZy0MGMQrpaj6HwCYsU8ZuDXtHE="
    secure: "ZjbUxO9j0T1bECreh6Juz0e0scrZEDdwcTeG3C3yS5Rd5vUJkY9Vw5R8KuQhhc3/2/MMj7S9x9pPGdtsyq4MU8EoFhLEWL/mWLqC1QhtDnyMQZSAwCBJbDsZrPoWBoZt0mUXKOeKxHc+nDtv82Kdu5h6XM5z6d6+03nuaztZDfGLL5fgJ5YeNkiJZTZJvNDbFWIUcVF/9CIJiVhJzXwO98tQ8ep+9ONHN3Uw6sbuCKXQ5yVV3AzBGtSW1rY8AmUGhv1IGLhdXKQ0bc6G2JMHOs70wBkAUNMKUHcC3w9jOi0+aLbMrnEf1Y5bGWjVoFLHLpK4/iwFLOlHU4rXIXCvCiaHNzsnHkcqa+t4UV409so6KZPDhu9Gr1zrS67IFdZUmbvU8qRgx311TjPKeFDFSdLyUX2Sj007DmgVPFcdd3Pjz72PTfDXl5H759T2SPeyq1SpJj2TQGrc4fPkLQx9GeUXi6bxG/P48BB3O7T975bYeuZZaEQxsyfFup/cfgAv4NjWpT2VxXHtTle2MPvDBefwvJHdZaLUKfCuDMcGjL1zChowuNdkOM+MADksXhIyCerDnHGkgW/r+4GOXjZ3w/8ynlTCj/TpGO4JntSApnjvBWA7M1Z5e5oHXAqBdDL2KjsXvVxIua6RyUlahj8LPaNMMG8NFFwCV2nG3GT0zKE="
