sudo: required
language: node_js
node_js:
- 6.9.1
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
install:
- git config --global user.email "test@test.com"
- git config --global user.name "Travis CI Test"
- export docuBranch=TravisCI
- npm run prepare
script:
- npm run init
- npm run compile
- npm run preparePushResult
- npm run pushResult
env:
  global:
    secure: "tuTNhyaNik+BpnJpRGP+cqgYk8fQnPWRF66Jg3nc0G8k/FdJrz+LHNYK07/NBRN34Fk7NEEiDD0t8LatG7TDUk9hyCeO6MVvk36JjGf1AI8eljQJ2AQw2wpM2RGnm/NfTKvOrTD9XiohRLtQz/B491lobaAW6wLBzK88qvPkx9oiYCMvHza/IiIKlqLVfmIsF9m10e+mmjMXl0KvB18YP2O3d91kitdJnbnY1eWXS9HmlUTVhpS0I8UkdxQeTwA1HvC2+/DsiadD2NKbwJhXt2++E/ylB8vdfVXn3J3UHkZhJPo70aAefIvyAcq4B1SAAd7we3/c7DFt5qoQ1ahtL5jCEMVOxGFsQjh20UXg+PF+r+jZYtXAJo3O82CbAKSGOiGkl22Fq4EyYToIyXsw6wewHAzIcnTfAmVaVcrWICBC6+lzlZXOwFN7WZ4sXG66C9aqQ5i4zAQiz43OexoeSPJLWczEIi1zg9Ym2mAzwYOjWGeEQkp96O+gfzMB/vbrEsxkltPYFaACouTOeVpKGMZMN1E2Cv4A+frYCUt1my6sdjQY0Q/J6y38F3L8EayU0sH/4loP8f/fZrJHhg3g0WpBh7Q2cbOApV5grwsCiszjKhzaW3bD8iXcbzb2CeNIVj4A0EKTs9jWTIhRwZy0MGMQrpaj6HwCYsU8ZuDXtHE="
