sudo: required
language: node_js
node_js:
  - "6.9.1"
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
install:
    - echo $GH_TOKEN
    - git config --global user.email "test@test.com"
    - git config --global user.name "Travis CI Test"
    - export docuBranch=TravisCI
    - npm run prepare
script:
    - npm run init
    - npm run compile
    - npm run preparePushResult
    - npm run pushResult
    
